<a href="https://colab.research.google.com/github/BrishavDebnath/Python/blob/main/Class_03_04_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install numpy

In [4]:
#Numpy
import numpy as np
list1=[1,2,3,4]
list2=[5,6,7,8]
list3=[20,5,2,0]
arr=np.array([list1,list2,list3])
print(arr)
Arr=arr.reshape(4,3)     # Reshapes arr according to given specifications.
print(Arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [20  5  2  0]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 20]
 [ 5  2  0]]


In [27]:
#Numpy arrays are faster than tuples and lists.
t1=(1,2,3,4)
t2=(5,6,7,8)
arr1=np.array(t1)
print(arr1)
arr2=np.array(t2)
print(arr2)
arr3=np.array([t1,t2])
print(arr3)
arr4=np.array(t1+t2)
print(arr4)
print(arr3[1:2,:2])
print(arr3[:,1:3])



[1 2 3 4]
[5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[[5 6]]
[[2 3]
 [6 7]]


In [32]:
arr5=np.arange(1,21).reshape(4,5)
print(arr5)
arr6=np.arange(1,20)
print(arr6)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [33]:
arr7=np.random.randint(0,50,4).reshape(2,2)    #a way to create arrays by randomly picking numbers and adding to a array.
print(arr7)                                    #(0,50,4) Here 4 means that 4 numbers are picked from 0 to 50 and added to array.

[[43 18]
 [39 37]]


In [35]:
#Pandas
import pandas as pd
import numpy as np

In [41]:
df=pd.DataFrame(data=np.arange(1,21).reshape(4,5),index=["Row1","Row2","Row3","Row4"],columns=["Col1","Col2","Col3","Col4","Col5"])
df.head()


Col1  Col2  Col3  Col4  Col5
Row1     1     2     3     4     5
Row2     6     7     8     9    10
Row3    11    12    13    14    15
Row4    16    17    18    19    20

In [42]:
df.tail()

Col1  Col2  Col3  Col4  Col5
Row1     1     2     3     4     5
Row2     6     7     8     9    10
Row3    11    12    13    14    15
Row4    16    17    18    19    20

In [43]:
df.describe()

Col1       Col2       Col3       Col4       Col5
count   4.000000   4.000000   4.000000   4.000000   4.000000
mean    8.500000   9.500000  10.500000  11.500000  12.500000
std     6.454972   6.454972   6.454972   6.454972   6.454972
min     1.000000   2.000000   3.000000   4.000000   5.000000
25%     4.750000   5.750000   6.750000   7.750000   8.750000
50%     8.500000   9.500000  10.500000  11.500000  12.500000
75%    12.250000  13.250000  14.250000  15.250000  16.250000
max    16.000000  17.000000  18.000000  19.000000  20.000000

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Row1 to Row4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    4 non-null      int64
 1   Col2    4 non-null      int64
 2   Col3    4 non-null      int64
 3   Col4    4 non-null      int64
 4   Col5    4 non-null      int64
dtypes: int64(5)
memory usage: 364.0+ bytes
